services:
  nginx:
    container_name: turborepo-starter-reverse-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./apps/proxy/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
