import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { after, before, describe, it } from "node:test";

const scriptPath = resolve(dirname(fileURLToPath(import.meta.url)), "../sync-agents.mjs");

const AGENT_SOURCE = `---
description: "Read-only fixture agent. Prefer invoking through the task tool."
mode: subagent
model: openai/gpt-fixture
hidden: true
options:
  reasoningEffort: xhigh
permission:
  "*": deny
  glob: allow
  grep: allow
  read: allow
  list: allow
  edit: deny
  bash:
    "*": deny
    "git diff*": allow
---

Fixture body with a quote block:

"""tricky toml"""
`;

function runSync(root) {
  return execFileSync(process.execPath, [scriptPath], {
    env: { ...process.env, SYNC_AGENTS_ROOT: root },
    encoding: "utf8",
  });
}

describe("sync-agents", () => {
  let root;

  before(() => {
    root = mkdtempSync(join(tmpdir(), "sync-agents-"));
    mkdirSync(join(root, ".opencode/agents"), { recursive: true });
    writeFileSync(join(root, ".opencode/agents/fixture.md"), AGENT_SOURCE);
    runSync(root);
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it("generates one definition per target tool", () => {
    for (const file of [
      ".claude/agents/fixture.md",
      ".codex/agents/fixture.toml",
      ".gemini/agents/fixture.md",
      ".github/agents/fixture.agent.md",
    ]) {
      assert.ok(existsSync(join(root, file)), `missing ${file}`);
      assert.match(readFileSync(join(root, file), "utf8"), /generated by scripts\/sync-agents\.mjs/);
    }
  });

  it("maps permissions to a Claude tool allowlist without model", () => {
    const claude = readFileSync(join(root, ".claude/agents/fixture.md"), "utf8");
    assert.match(claude, /^name: fixture$/m);
    assert.match(claude, /^tools: Read, Grep, Glob, Bash$/m);
    assert.doesNotMatch(claude, /gpt-fixture/);
    assert.doesNotMatch(claude, /^model:/m);
  });

  it("emits Codex TOML with sandbox, reasoning effort, and escaped body", () => {
    const codex = readFileSync(join(root, ".codex/agents/fixture.toml"), "utf8");
    assert.match(codex, /^name = "fixture"$/m);
    assert.match(codex, /^sandbox_mode = "read-only"$/m);
    assert.match(codex, /^model_reasoning_effort = "xhigh"$/m);
    assert.match(codex, /developer_instructions = """\n/);
    // The body's `"""` must be broken so it cannot terminate the TOML string.
    assert.doesNotMatch(codex, /tricky toml"""\n/);
    assert.match(codex, /""\\"tricky toml""\\"/);
  });

  it("maps permissions to Gemini tool names", () => {
    const gemini = readFileSync(join(root, ".gemini/agents/fixture.md"), "utf8");
    assert.match(gemini, /- read_file/);
    assert.match(gemini, /- search_file_content/);
    assert.match(gemini, /- run_shell_command/);
    assert.doesNotMatch(gemini, /write_file/);
  });

  it("writes generated files read-only so in-place edits fail", () => {
    const filePath = join(root, ".claude/agents/fixture.md");
    assert.equal(statSync(filePath).mode & 0o222, 0, "generated file is writable");
    assert.throws(() => writeFileSync(filePath, "sneaky edit\n"), /EACCES|EPERM/);
  });

  it("replaces a read-only generated file when the source changes", () => {
    writeFileSync(
      join(root, ".opencode/agents/fixture.md"),
      AGENT_SOURCE.replace("Fixture body", "Updated body"),
    );

    runSync(root);

    const claude = readFileSync(join(root, ".claude/agents/fixture.md"), "utf8");
    assert.match(claude, /Updated body/);
    assert.equal(statSync(join(root, ".claude/agents/fixture.md")).mode & 0o222, 0);

    // Restore the original source and outputs for the remaining tests.
    writeFileSync(join(root, ".opencode/agents/fixture.md"), AGENT_SOURCE);
    runSync(root);
  });

  it("is idempotent (second run writes nothing)", () => {
    assert.equal(runSync(root).trim(), "");
  });

  it("removes stale generated files but preserves hand-written ones", () => {
    const handWritten = join(root, ".claude/agents/local-only.md");
    writeFileSync(handWritten, "---\nname: local-only\n---\nkeep me\n");
    rmSync(join(root, ".opencode/agents/fixture.md"));

    runSync(root);

    assert.ok(!existsSync(join(root, ".claude/agents/fixture.md")));
    assert.ok(!existsSync(join(root, ".codex/agents/fixture.toml")));
    assert.ok(existsSync(handWritten), "hand-written agent was deleted");

    // Restore the fixture for any later assertions.
    writeFileSync(join(root, ".opencode/agents/fixture.md"), AGENT_SOURCE);
    runSync(root);
  });

  it("never overwrites a hand-written file at a generated path", () => {
    const conflictPath = join(root, ".gemini/agents/fixture.md");
    rmSync(conflictPath, { force: true });
    writeFileSync(conflictPath, "hand-written, no marker\n");

    const { status, stderr } = spawnSync(process.execPath, [scriptPath], {
      env: { ...process.env, SYNC_AGENTS_ROOT: root },
      encoding: "utf8",
    });

    assert.equal(status, 0);
    assert.equal(readFileSync(conflictPath, "utf8"), "hand-written, no marker\n");
    assert.match(stderr, /skipped \.gemini\/agents\/fixture\.md/);
  });

  it("skips gracefully when .opencode/agents is missing", () => {
    const emptyRoot = mkdtempSync(join(tmpdir(), "sync-agents-empty-"));
    try {
      const output = execFileSync(process.execPath, [scriptPath], {
        env: { ...process.env, SYNC_AGENTS_ROOT: emptyRoot },
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      });
      assert.equal(output.trim(), "");
    } finally {
      rmSync(emptyRoot, { recursive: true, force: true });
    }
  });
});
