// Generates tool-native agent definitions from the canonical opencode agents
// in `.opencode/agents/*.md`, so Claude Code, Codex CLI, Gemini CLI, and
// GitHub Copilot CLI can all invoke the same subagents without duplicating
// their prompts.
//
// Unlike skills (see scripts/link-agent-skills.mjs), agent frontmatter is NOT
// portable across tools, so this script converts instead of symlinking:
//
//   .opencode/agents/<name>.md  (canonical, committed)
//     -> .claude/agents/<name>.md          Claude Code (MD + frontmatter)
//     -> .codex/agents/<name>.toml         Codex CLI (TOML)
//     -> .gemini/agents/<name>.md          Gemini CLI (MD + frontmatter)
//     -> .grok/agents/<name>.md            Grok Build (MD + frontmatter)
//     -> .github/agents/<name>.agent.md    Copilot CLI (MD + frontmatter)
//
// The conversion is intentionally lossy: opencode's per-glob bash permissions
// cannot be expressed in the other tools' frontmatter, so they are rounded to
// the nearest coarse posture (tool allowlists / sandbox mode) and the prompt
// body keeps carrying the fine-grained rules. `model` is never emitted — the
// generated agents inherit the invoking tool's model. `hidden`, `mode`, and
// opencode-only options are dropped.
//
// Idempotent and safe to re-run. Only files containing the GENERATED_MARKER
// are ever overwritten or deleted, so hand-written local agents survive.
// Outputs are written read-only (0444) so nothing edits them in place.
// Wired into `postinstall` (see package.json); run manually with
// `nps sync.agents` or `node scripts/sync-agents.mjs`.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = process.env.SYNC_AGENTS_ROOT
  ? resolve(process.env.SYNC_AGENTS_ROOT)
  : resolve(dirname(fileURLToPath(import.meta.url)), "..");

const GENERATED_MARKER = "generated by scripts/sync-agents.mjs";
const GENERATED_NOTE = `${GENERATED_MARKER} — do not edit; edit .opencode/agents/ instead`;

function main() {
  const sourceDir = ["agents", "agent"]
    .map((d) => join(repoRoot, ".opencode", d))
    .find((d) => existsSync(d));

  if (!sourceDir) {
    // e.g. a pruned CI workspace — nothing to sync, never fail the install.
    console.warn("[sync-agents] .opencode/agents not found; skipping.");
    return;
  }

  const agents = readdirSync(sourceDir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => parseAgent(join(sourceDir, f)))
    .filter(Boolean);

  const targets = [
    { dir: ".claude/agents", ext: ".md", emit: emitClaude },
    { dir: ".codex/agents", ext: ".toml", emit: emitCodex },
    { dir: ".gemini/agents", ext: ".md", emit: emitGemini },
    { dir: ".grok/agents", ext: ".md", emit: emitGrok },
    { dir: ".github/agents", ext: ".agent.md", emit: emitCopilot },
  ];

  for (const target of targets) {
    const outDir = join(repoRoot, target.dir);
    mkdirSync(outDir, { recursive: true });

    const expected = new Set(agents.map((a) => `${a.name}${target.ext}`));

    // Delete stale files we generated for agents that no longer exist. Files
    // without the marker (hand-written) are always left untouched.
    for (const file of readdirSync(outDir)) {
      const filePath = join(outDir, file);
      if (expected.has(file)) continue;
      if (!isGenerated(filePath)) continue;
      rmSync(filePath);
      console.log(`[sync-agents] removed stale ${target.dir}/${file}`);
    }

    for (const agent of agents) {
      const filePath = join(outDir, `${agent.name}${target.ext}`);
      if (existsSync(filePath) && !isGenerated(filePath)) {
        console.warn(
          `[sync-agents] skipped ${target.dir}/${agent.name}${target.ext} (exists and is not generated)`,
        );
        continue;
      }
      const content = target.emit(agent);
      if (existsSync(filePath) && readFileSync(filePath, "utf8") === content) {
        continue;
      }
      // Write read-only (0444): editors and AI tools get a permission error
      // instead of silently editing a file the next sync would clobber. The
      // sync itself replaces files by unlinking first, so it is unaffected.
      rmSync(filePath, { force: true });
      writeFileSync(filePath, content, { mode: 0o444 });
      console.log(`[sync-agents] wrote ${target.dir}/${agent.name}${target.ext}`);
    }
  }
}

function parseAgent(filePath) {
  const raw = readFileSync(filePath, "utf8");
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) {
    console.warn(`[sync-agents] ${basename(filePath)} has no frontmatter; skipping.`);
    return null;
  }

  let frontmatter;
  try {
    frontmatter = parseFrontmatterMap(match[1]);
  } catch (error) {
    console.warn(`[sync-agents] ${basename(filePath)}: invalid frontmatter (${error.message}); skipping.`);
    return null;
  }

  if (!frontmatter.description) {
    console.warn(`[sync-agents] ${basename(filePath)} has no description; skipping.`);
    return null;
  }

  return {
    name: basename(filePath, ".md"),
    description: String(frontmatter.description),
    body: match[2].trim(),
    capabilities: deriveCapabilities(frontmatter.permission ?? {}),
    reasoningEffort: frontmatter.options?.reasoningEffort,
  };
}

// Rounds opencode's permission map down to coarse per-capability booleans.
// A capability counts as enabled when any of its patterns is `allow` or `ask`
// (`ask` still surfaces the tool; only a blanket `deny` removes it).
function deriveCapabilities(permission) {
  const fallback = permission["*"] ?? "allow";
  const enabled = (key) => {
    const value = permission[key] ?? fallback;
    const actions = typeof value === "object" && value !== null ? Object.values(value) : [value];
    return actions.some((action) => action === "allow" || action === "ask");
  };
  return {
    read: enabled("read"),
    grep: enabled("grep"),
    glob: enabled("glob"),
    list: enabled("list"),
    edit: enabled("edit"),
    bash: enabled("bash"),
    webfetch: enabled("webfetch"),
    websearch: enabled("websearch"),
  };
}

function isGenerated(filePath) {
  try {
    return readFileSync(filePath, "utf8").includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

function frontmatterDocument(fields, body) {
  const lines = [];
  for (const [key, value] of Object.entries(fields)) {
    if (Array.isArray(value)) {
      lines.push(`${key}:`);
      for (const item of value) lines.push(`  - ${yamlScalar(item)}`);
    } else {
      lines.push(`${key}: ${yamlScalar(value)}`);
    }
  }
  return `---\n# ${GENERATED_NOTE}\n${lines.join("\n")}\n---\n\n${body}\n`;
}

// Emit a value as a plain YAML scalar when that is unambiguous, otherwise as
// a JSON string (every JSON string is a valid YAML double-quoted scalar).
function yamlScalar(value) {
  const text = String(value);
  const plainSafe =
    /^[A-Za-z0-9_][A-Za-z0-9_.,/* -]*$/.test(text) &&
    !text.includes(": ") &&
    !text.includes(" #") &&
    !text.endsWith(" ");
  return plainSafe ? text : JSON.stringify(text);
}

// --- Frontmatter parsing -----------------------------------------------------
//
// Minimal parser for the YAML subset this repo's agent frontmatter actually
// uses, so the script stays dependency-free (the script-tests CI job runs
// without an install step): nested maps via 2-space indentation, bare or
// double-quoted keys, and bare / double-quoted / single-quoted scalar values.
// Lists, block scalars, flow collections, and anchors are NOT supported —
// parsing throws, and the caller skips that agent with a warning instead of
// emitting a wrong conversion.

function parseFrontmatterMap(text) {
  const root = {};
  const stack = [{ indent: -1, value: root }];
  const lines = text.split(/\r?\n/);

  for (let i = 0; i < lines.length; i++) {
    const lineNo = i + 1;
    const line = lines[i];
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) continue;

    const indent = line.length - line.trimStart().length;
    if (indent % 2 !== 0) throw new Error(`odd indentation at line ${lineNo}`);
    if (trimmed === "-" || trimmed.startsWith("- ")) {
      throw new Error(`lists are not supported (line ${lineNo})`);
    }

    const { key, rest } = splitKey(trimmed, lineNo);

    while (stack.length > 1 && indent <= stack[stack.length - 1].indent) {
      stack.pop();
    }
    const parent = stack[stack.length - 1].value;

    if (rest === "") {
      const child = {};
      parent[key] = child;
      stack.push({ indent, value: child });
    } else {
      parent[key] = parseScalar(rest, lineNo);
    }
  }

  return root;
}

function splitKey(entry, lineNo) {
  if (entry.startsWith('"')) {
    const match = entry.match(/^("(?:[^"\\]|\\.)*")\s*:\s*(.*)$/);
    if (!match) throw new Error(`unterminated quoted key at line ${lineNo}`);
    return { key: JSON.parse(match[1]), rest: match[2] };
  }
  const match = entry.match(/^([^:"']+?)\s*:\s*(.*)$/);
  if (!match) throw new Error(`expected "key: value" at line ${lineNo}`);
  return { key: match[1], rest: match[2] };
}

function parseScalar(text, lineNo) {
  if (text.startsWith('"')) {
    if (!/^"(?:[^"\\]|\\.)*"$/.test(text)) {
      throw new Error(`unsupported quoted value at line ${lineNo}`);
    }
    return JSON.parse(text);
  }
  if (text.startsWith("'")) {
    const match = text.match(/^'((?:[^']|'')*)'$/);
    if (!match) throw new Error(`unsupported quoted value at line ${lineNo}`);
    return match[1].replaceAll("''", "'");
  }
  if (text === "true") return true;
  if (text === "false") return false;
  if (text.startsWith("{") || text.startsWith("[") || text.startsWith("&") || text.startsWith("|") || text.startsWith(">")) {
    throw new Error(`unsupported YAML syntax at line ${lineNo}`);
  }
  return text;
}

// --- Claude Code: .claude/agents/<name>.md ---------------------------------
// https://code.claude.com/docs/en/subagents

function emitClaude(agent) {
  const c = agent.capabilities;
  const tools = [
    ...(c.read ? ["Read"] : []),
    ...(c.grep ? ["Grep"] : []),
    ...(c.glob || c.list ? ["Glob"] : []),
    ...(c.edit ? ["Edit", "Write"] : []),
    ...(c.bash ? ["Bash"] : []),
    ...(c.webfetch ? ["WebFetch"] : []),
    ...(c.websearch ? ["WebSearch"] : []),
  ];
  return frontmatterDocument(
    {
      name: agent.name,
      description: agent.description,
      tools: tools.join(", "),
    },
    agent.body,
  );
}

// --- Codex CLI: .codex/agents/<name>.toml ----------------------------------
// https://developers.openai.com/codex/subagents

const CODEX_REASONING_EFFORTS = new Set(["minimal", "low", "medium", "high", "xhigh"]);

function emitCodex(agent) {
  const lines = [
    `# ${GENERATED_NOTE}`,
    `name = ${tomlString(agent.name)}`,
    `description = ${tomlString(agent.description)}`,
    `sandbox_mode = ${tomlString(agent.capabilities.edit ? "workspace-write" : "read-only")}`,
  ];
  if (CODEX_REASONING_EFFORTS.has(agent.reasoningEffort)) {
    lines.push(`model_reasoning_effort = ${tomlString(agent.reasoningEffort)}`);
  }
  lines.push(`developer_instructions = ${tomlMultiline(agent.body)}`);
  return `${lines.join("\n")}\n`;
}

function tomlString(value) {
  return JSON.stringify(String(value));
}

function tomlMultiline(value) {
  // TOML multi-line basic string: escape backslashes, then break any `"""`.
  const escaped = String(value).replaceAll("\\", "\\\\").replaceAll('"""', '""\\"');
  return `"""\n${escaped}\n"""`;
}

// --- Gemini CLI: .gemini/agents/<name>.md -----------------------------------
// https://geminicli.com/docs/core/subagents/

function emitGemini(agent) {
  const c = agent.capabilities;
  const tools = [
    ...(c.read ? ["read_file", "read_many_files"] : []),
    ...(c.grep ? ["search_file_content"] : []),
    ...(c.glob ? ["glob"] : []),
    ...(c.list ? ["list_directory"] : []),
    ...(c.edit ? ["write_file", "replace"] : []),
    ...(c.bash ? ["run_shell_command"] : []),
    ...(c.webfetch ? ["web_fetch"] : []),
    ...(c.websearch ? ["google_web_search"] : []),
  ];
  return frontmatterDocument(
    {
      name: agent.name,
      description: agent.description,
      tools,
    },
    agent.body,
  );
}

// --- Grok Build: .grok/agents/<name>.md --------------------------------------

function emitGrok(agent) {
  const c = agent.capabilities;
  const tools = [
    ...(c.read ? ["read_file"] : []),
    ...(c.grep ? ["grep"] : []),
    ...(c.glob || c.list ? ["list_dir"] : []),
    ...(c.edit ? ["search_replace"] : []),
    ...(c.bash ? ["run_terminal_command"] : []),
    ...(c.webfetch ? ["web_fetch"] : []),
    ...(c.websearch ? ["web_search"] : []),
  ];
  return frontmatterDocument(
    {
      name: agent.name,
      description: agent.description,
      tools,
    },
    agent.body,
  );
}

// --- Copilot CLI: .github/agents/<name>.agent.md ----------------------------
// https://docs.github.com/en/copilot/how-tos/copilot-cli/customize-copilot/create-custom-agents-for-cli
//
// Copilot's tool identifiers differ per surface, so no `tools` allowlist is
// emitted; the prompt body carries the read-only / scope rules instead.

function emitCopilot(agent) {
  return frontmatterDocument(
    {
      name: agent.name,
      description: agent.description,
    },
    agent.body,
  );
}

main();
